Fix CI/CD - Esperar más a lenvantar aplicaciones antes de smoke test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -42,16 +42,23 @@ jobs:
 
       - name: Verificar API (Port 8000)
         run: |
-          sleep 20
-          # Intentamos conectar a la API. Usamos localhost porque Docker mapea los puertos al host del runner (la máquina que ejecuta la acción en GitHub).
-          curl -f http://localhost:8000/api/test || exit 1
-          echo "La API responde correctamente!"
+          # En esto, --retry-connrefused reintenta si el puerto aún no está abierto, y -v muestra información detallada
+          echo "Esperando a que la API esté lista en localhost:8000..."
+          curl --retry 10 \
+          --retry-delay 5 \
+          --retry-connrefused \
+          -v http://localhost:8000/api/test || exit 1
+          echo "La API responde correctamente!"          
 
       - name: Verificar Web (Port 8080)
         run: |
-          curl -f http://localhost:8080/login || exit 1
-          # Intentamos conectar a la web. Usamos localhost porque Docker mapea los puertos al host del runner (la máquina que ejecuta la acción en GitHub).
-          echo "La Web responde correctamente!"
+          # En esto, --retry-connrefused reintenta si el puerto aún no está abierto, y -v muestra información detallada
+          echo "Esperando a que la web esté lista en localhost:8080..."
+          curl --retry 10 \
+          --retry-delay 5 \
+          --retry-connrefused \
+          -v http://localhost:8080/login || exit 1
+          echo "La web responde correctamente!"  
 
       - name: Logs en caso de fallo
         if: failure()
